CREATE DATABASE email_sender;

\c email_sender

CREATE TABLE EMAILS (
    ID SERIAL NOT NULL,
    DATA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ASSUNTO VARCHAR(100) NOT NULL,
    MENSAGEM VARCHAR(250) NOT NULL
);